######################################################################
# Automatically generated by qmake (2.01a) Thu May 5 00:25:01 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h qcustomplot.h UdpServer.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp qcustomplot.cpp UdpServer.cpp
LIBS += -lstdc++ -lpulse-simple -lpulse -lfftw3 -lm